---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: "/srv/jekyll/_site"
  preview_docker_image: jekyll/builder
  mount_path: "/srv/jekyll"
  instant_preview_command: jekyll serve --drafts --unpublished --future --port 8080
    --host 0.0.0.0 -d _site
  preview_command: jekyll build --drafts --unpublished --future -d _site
