name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to Production
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        privateKey: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        local: "_site/*"
        remote: "public_html/sitetest/*"

